import type { FrameworkTemplate } from './types'

// Library of quadrant models. Ordered Core-first (broad, instantly understood)
// then Extended (narrower), then the original retro-style presets. Spec and
// rationale live in work/0-research/quadrant-model-library.md.
export const templates: FrameworkTemplate[] = [
  // ── Core ──────────────────────────────────────────────────────────────
  {
    name: 'Eisenhower Matrix',
    axisX: 'Urgency',
    axisY: 'Importance',
    quadrants: ['Schedule', 'Do First', 'Eliminate', 'Delegate'],
    colors: ['#60a5fa', '#4ade80', '#94a3b8', '#fbbf24'],
    description: 'Separate what truly matters from what merely feels urgent.',
  },
  {
    name: 'Impact / Effort',
    axisX: 'Effort',
    axisY: 'Impact',
    quadrants: ['Quick Wins', 'Big Bets', 'Fill-Ins', 'Thankless Tasks'],
    colors: ['#4ade80', '#60a5fa', '#fbbf24', '#94a3b8'],
    description: 'Find the quick wins by weighing value against cost.',
  },
  {
    name: 'One-Way / Two-Way Doors',
    axisX: 'Consequence',
    axisY: 'Reversibility',
    quadrants: ['Just Decide', 'Experiment', "Don't Agonize", 'Deliberate'],
    colors: ['#4ade80', '#60a5fa', '#fbbf24', '#ef4444'],
    description: 'Match decision effort to how reversible the choice is.',
  },
  {
    name: 'Risk Matrix',
    axisX: 'Likelihood',
    axisY: 'Impact',
    quadrants: ['Plan Contingency', 'Mitigate Now', 'Accept', 'Monitor'],
    colors: ['#fbbf24', '#ef4444', '#4ade80', '#f97316'],
    description: 'Rank risks by how likely they are against how bad they are.',
  },
  {
    name: 'Growth–Share Matrix',
    axisX: 'Market Share',
    axisY: 'Market Growth',
    quadrants: ['Question Marks', 'Stars', 'Dogs', 'Cash Cows'],
    colors: ['#a78bfa', '#fbbf24', '#94a3b8', '#4ade80'],
    description: 'Decide what to feed, milk, or drop across a portfolio.',
  },
  {
    name: 'Power × Interest',
    axisX: 'Interest',
    axisY: 'Power',
    quadrants: ['Keep Satisfied', 'Manage Closely', 'Monitor', 'Keep Informed'],
    colors: ['#fbbf24', '#ef4444', '#94a3b8', '#60a5fa'],
    description: 'Manage stakeholders by their power and their interest.',
  },
  {
    name: 'Skill × Will',
    axisX: 'Skill',
    axisY: 'Will',
    quadrants: ['Guide', 'Delegate', 'Direct', 'Motivate'],
    colors: ['#60a5fa', '#4ade80', '#fbbf24', '#f97316'],
    description: 'Coach each person by their skill paired with their motivation.',
  },
  {
    name: 'Passion × Proficiency',
    axisX: 'Good At It',
    axisY: 'Love It',
    quadrants: ['Invest', 'Sweet Spot', 'Avoid', 'Burnout Zone'],
    colors: ['#60a5fa', '#4ade80', '#94a3b8', '#f97316'],
    description: 'Audit work by what you are good at versus what you love.',
  },
  {
    name: 'Mood Meter',
    axisX: 'Pleasantness',
    axisY: 'Energy',
    quadrants: ['Tense', 'Excited', 'Down', 'Calm'],
    colors: ['#ef4444', '#fbbf24', '#60a5fa', '#4ade80'],
    description: 'Name an emotion by its pleasantness and its energy.',
  },
  // ── Extended ──────────────────────────────────────────────────────────
  {
    name: 'Ansoff Matrix',
    axisX: 'Existing / New Products',
    axisY: 'Existing / New Markets',
    quadrants: ['Market Development', 'Diversification', 'Market Penetration', 'Product Development'],
    colors: ['#fbbf24', '#ef4444', '#4ade80', '#fbbf24'],
    description: 'Plan growth by how new the product and the market are to you.',
  },
  {
    name: 'Vision × Execution',
    axisX: 'Completeness of Vision',
    axisY: 'Ability to Execute',
    quadrants: ['Challengers', 'Leaders', 'Niche Players', 'Visionaries'],
    colors: ['#60a5fa', '#4ade80', '#94a3b8', '#a78bfa'],
    description: 'Compare players by vision against ability to deliver.',
  },
  {
    name: 'Knowns & Unknowns',
    axisX: 'Knowledge',
    axisY: 'Awareness',
    quadrants: ['Known Unknowns', 'Known Knowns', 'Unknown Unknowns', 'Unknown Knowns'],
    colors: ['#60a5fa', '#4ade80', '#ef4444', '#a78bfa'],
    description: 'Surface what you know, what you do not, and what you assume.',
  },
  {
    name: 'Certainty × Agreement',
    axisX: 'Certainty',
    axisY: 'Agreement',
    quadrants: ['Experiment', 'Plan', 'Stabilize', 'Negotiate'],
    colors: ['#a78bfa', '#4ade80', '#ef4444', '#fbbf24'],
    description: 'Choose how to work as certainty and alignment vary.',
  },
  {
    name: 'Johari Window',
    axisX: 'Known to Self',
    axisY: 'Known to Others',
    quadrants: ['Blind Spot', 'Open', 'Unknown', 'Hidden'],
    colors: ['#fbbf24', '#4ade80', '#94a3b8', '#60a5fa'],
    description: 'Grow self-awareness through feedback and disclosure.',
  },
  {
    name: 'Competence Ladder',
    axisX: 'Competence',
    axisY: 'Awareness',
    quadrants: ['Conscious Incompetence', 'Conscious Competence', 'Unconscious Incompetence', 'Unconscious Competence'],
    colors: ['#fbbf24', '#60a5fa', '#94a3b8', '#4ade80'],
    description: 'Locate where you are on the path from novice to mastery.',
  },
  {
    name: 'Importance × Satisfaction',
    axisX: 'Satisfaction',
    axisY: 'Importance',
    quadrants: ['Focus Here', 'Keep It Up', 'Low Priority', 'Overkill'],
    colors: ['#f97316', '#4ade80', '#94a3b8', '#fbbf24'],
    description: 'Spot opportunities users care about but rate poorly today.',
  },
  {
    name: 'Worry Matrix',
    axisX: 'Control',
    axisY: 'Importance',
    quadrants: ['Accept & Adapt', 'Take Action', 'Let It Go', 'Not Worth It'],
    colors: ['#34d399', '#4ade80', '#94a3b8', '#fbbf24'],
    description: 'Focus worry where you have both stakes and control.',
  },
  {
    name: 'How–Now–Wow',
    axisX: 'Originality',
    axisY: 'Ease of Implementation',
    quadrants: ['Now', 'Wow', 'Ciao', 'How'],
    colors: ['#60a5fa', '#fbbf24', '#94a3b8', '#a78bfa'],
    description: 'Triage brainstormed ideas by originality and ease.',
  },
  // ── Retro-style presets (original library) ──────────────────────────────
  {
    name: 'Start / Stop / Continue / Change',
    axisX: 'Existing / New',
    axisY: 'Rethink / Embrace',
    quadrants: ['Continue', 'Start', 'Stop', 'Change'],
    colors: ['#4ade80', '#60a5fa', '#ef4444', '#fbbf24'],
    description: 'Retro your habits: what to start, stop, continue, or change.',
  },
  {
    name: 'Keep / Problem / Try / Question',
    axisX: '',
    axisY: '',
    quadrants: ['Keep', 'Problem', 'Try', 'Question'],
    colors: ['#4ade80', '#ef4444', '#60a5fa', '#a78bfa'],
    description: 'A lightweight retro: what to keep, fix, try, or question.',
  },
  {
    name: 'Love / Loathe / Learn / Leave',
    axisX: '',
    axisY: '',
    quadrants: ['Love', 'Loathe', 'Learn', 'Leave'],
    colors: ['#f472b6', '#ef4444', '#60a5fa', '#94a3b8'],
    description: 'Reflect on what energizes you and what drains you.',
  },
  {
    name: 'SWOT Analysis',
    axisX: 'Helpful / Harmful',
    axisY: 'External / Internal',
    quadrants: ['Strengths', 'Weaknesses', 'Opportunities', 'Threats'],
    colors: ['#4ade80', '#ef4444', '#60a5fa', '#f97316'],
    description: 'Assess strengths, weaknesses, opportunities, and threats.',
  },
  {
    name: 'CRR — Cooperative Reciprocal Relationships',
    axisX: '',
    axisY: '',
    quadrants: ['Is Working', 'Desire', 'Get Rid Of', 'Renegotiate'],
    colors: ['#4ade80', '#60a5fa', '#94a3b8', '#fbbf24'],
    description: 'Review a relationship: what works, what to change or renegotiate.',
  },
]
